[project]
name = "repl-nix-geolinguisticmapper"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.19.3",
    "geoalchemy2>=0.16.0",
    "openai>=1.58.1",
    "pandas>=2.2.3",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.36",
    "streamlit>=1.41.1",
    "streamlit-folium>=0.24.0",
]
